# Generated by Django 5.2.3 on 2025-06-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
