# Generated by Django 5.2.3 on 2025-06-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0002_alter_package_name_alter_packagedetail_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='activation_code',
            field=models.CharField(max_length=50),
        ),
    ]
