# Generated by Django 5.2.3 on 2025-06-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('service', 'Service Based'), ('bundle', 'Bundle Based')], default='service', max_length=50),
        ),
    ]
