# Generated by Django 5.2.3 on 2025-06-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0005_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='button_active',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='button_check_blance',
            field=models.CharField(default='Check blance', max_length=50),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='button_deactive',
            field=models.CharField(default='Deactive', max_length=50),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='code',
            field=models.CharField(default='#123..*', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
