# Generated by Django 5.2.3 on 2025-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0006_packagedetail_button_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='type',
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
