# Generated by Django 5.2.3 on 2025-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0007_remove_package_type_alter_packagedetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetail',
            name='activation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='check_balance_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='packagedetail',
            name='deactivation_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
