# Generated by Django 5.2.3 on 2025-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0008_alter_packagedetail_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='is_services',
            field=models.BooleanField(default=False),
        ),
    ]
