# Generated by Django 5.2.3 on 2025-07-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AfgNetwors', '0010_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetail',
            name='button_active',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='button_check_blance',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='button_deactive',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='code',
        ),
        migrations.RemoveField(
            model_name='packagedetail',
            name='description',
        ),
    ]
